#pragma once

#include <mkl.h>

typedef long long int llong;
typedef unsigned long ulong;
typedef unsigned long long ullong;

const llong MKL_IFS_SIZE = 64LL;

// PARDISO-specific parameters - refer to
// https://software.intel.com/en-us/node/521690

// Matrix types - mtype
const llong MKL_PARDISO_MATRIX_TYPE_REAL_STRUCT_SYMMETRIC = 1;
const llong MKL_PARDISO_MATRIX_TYPE_REAL_SYMMETRIC_POS_DEF = 2;
const llong MKL_PARDISO_MATRIX_TYPE_REAL_SYMMETRIC_INDEF = -2;
const llong MKL_PARDISO_MATRIX_TYPE_COMPLEX_STRUCT_SYMMETRIC = 3;
const llong MKL_PARDISO_MATRIX_TYPE_COMPLEX_HERMITIAN_POS_DEF = 4;
const llong MKL_PARDISO_MATRIX_TYPE_COMPLEX_HERMITIAN_INDEX = -4;
const llong MKL_PARDISO_MATRIX_TYPE_COMPLEX_SYMMETRIC = 6;
const llong MKL_PARDISO_MATRIX_TYPE_REAL_UNSYMMETRIC = 11;
const llong MKL_PARDISO_MATRIX_TYPE_COMPLEX_UNSYMMETRIC = 13;

// Solver phases - phase
const llong MKL_PARDISO_SOLVER_PHASE_ANALYSIS = 11;
const llong MKL_PARDISO_SOLVER_PHASE_ANALYSIS_NUMERICAL_FACTORIZATION = 12;
const llong MKL_PARDISO_SOLVER_PHASE_ANALYSIS_NUMERICAL_FACTORIZATION_SOLVE = 13;
const llong MKL_PARDISO_SOLVER_PHASE_NUMERICAL_FACTORIZATION = 22;
const llong MKL_PARDISO_SOLVER_PHASE_NUMERICAL_FACTORIZATION_SOLVE = 23;
const llong MKL_PARDISO_SOLVER_PHASE_SOLVE_ITERATIVE_REFINEMENT = 33;
const llong MKL_PARDISO_SOLVER_PHASE_SOLVE_FORWARD_SUBSTITUTION = 331;
const llong MKL_PARDISO_SOLVER_PHASE_SOLVE_DIAGONAL_SUBSTITUTION = 332;
const llong MKL_PARDISO_SOLVER_PHASE_SOLVE_BACKWARD_SUBSTITUTION = 333;
const llong MKL_PARDISO_SOLVER_PHASE_RELEASE_MEMORY_MNUM = 0;
const llong MKL_PARDISO_SOLVER_PHASE_RELEASE_MEMORY_ALL = -1;

// PARDISO IPARM - refer to https://software.intel.com/en-us/node/521691
const llong MKL_PARDISO_NA = 100;
const llong MKL_PARDISO_DEFAULT = 0;
const llong MKL_PARDISO_FALSE = 1;
const llong MKL_PARDISO_REPORT_ENABLE = -1;
const llong MKL_PARDISO_REPORT_DISABLE = 0;

const llong MKL_PARDISO_DEFAULT_SETTINGS = 0;

const llong MKL_PARDISO_FILL_IN_REDUCING_ORDERING_OPTION = 1;
const llong MKL_PARDISO_FILL_IN_REDUCING_ORDERING_MIN_DEGREE = 0;
const llong MKL_PARDISO_FILL_IN_REDUCING_ORDERING_NESTED_DISSECTION_METIS = 2;
const llong MKL_PARDISO_FILL_IN_REDUCING_ORDERING_NESTED_DISSECTION_OMP = 3;

const llong MKL_PARDISO_PRECONDITIONED_CGS_CG = 3;
const llong MKL_PARDISO_PRECONDITIONED_DEFAULT = 0;

const llong MKL_PARDISO_PERMUTATION_OPTION = 4;
const llong MKL_PARDISO_PERMUTATION_USE_PERM = 1;
const llong MKL_PARDISO_PERMUTATION_RETURN = 2;

const llong MKL_PARDISO_RETURN_OPTION = 5;
const llong MKL_PARDISO_RETURN_OVERRIDE = 1;

const llong MKL_PARDISO_REPORT_ITERATIVE_STEPS_USED = 6;

const llong MKL_PARDISO_ITERATIVE_REFINEMENT_MAX = 7;

const llong MKL_PARDISO_PIVOTING_PERTURBATION = 9;

const llong MKL_PARDISO_SCALING_OPTION = 10;
const llong MKL_PARDISO_SCALING_ENABLE = 1;

const llong MKL_PARDISO_SOLVE_OPTION = 11;
const llong MKL_PARDISO_SOLVE_CONJUGATE_TRANSPOSED = 1;
const llong MKL_PARDISO_SOLVE_TRANSPOSED = 2;

const llong MKL_PARDISO_WEIGHTED_MATCHING_OPTION = 12;
const llong MKL_PARDISO_WEIGHTED_MATCHING_DISABLE = 0;
const llong MKL_PARDISO_WEIGHTED_MATCHING_ENABLE = 1;

const llong MKL_PARDISO_N_PERTURBED_PIVOTS = 13;

const llong MKL_PARDISO_PEAK_MEMORY_SYMBOLIC_PHASE = 14;
const llong MKL_PARDISO_PERMANENT_MEMORY_SYMBOLIC_PHASE = 15;
const llong MKL_PARDISO_PEAK_MEMORY_NUMERIC_PHASE = 16;

const llong MKL_PARDISO_REPORT_NNZ_FACTORS = 17;
const llong MKL_PARDISO_REPORT_FLOP_FACTOR_PHASE = 18;
const llong MKL_PARDISO_REPORT_CGS_CG_DIAGNOSTIC = 19;

const llong MKL_PARDISO_PIVOT_SYMMETRIC_INDEF_OPTION = 20;
const llong MKL_PARDISO_PIVOT_SYMMETRIC_INDEF_DIAG = 0;
const llong MKL_PARDISO_PIVOT_SYMMETRIC_INDEF_BUNCH_KAUFMAN = 1;
const llong MKL_PARDISO_PIVOT_SYMMETRIC_INDEF_DIAG_NO_AUTO = 2;
const llong MKL_PARDISO_PIVOT_SYMMETRIC_INDEF_BUNCH_KAUFMAN_NO_AUTO = 3;

const llong MKL_PARDISO_POS_EIGENVALUES = 21;
const llong MKL_PARDISO_NEG_EIGENVALUES = 22;

const llong MKL_PARDISO_PARALLEL_FACTORIZATION_OPTION = 23;
const llong MKL_PARDISO_PARALLEL_FACTORIZATION_TWO_LEVEL = 1;
const llong MKL_PARDISO_PARALLEL_FACTORIZATION_TWO_LEVEL_IMPROVED = 10;

const llong MKL_PARDISO_PARALLEL_SOLVE_OPTION = 24;
const llong MKL_PARDISO_SEQUENTIAL_SOLVE = 1;

const llong MKL_PARDISO_MATRIX_CHECK_OPTION = 26;
const llong MKL_PARDISO_MATRIX_CHECK_ENABLE = 1;

const llong MKL_PARDISO_PRECISION_OPTION = 27;
const llong MKL_PARDISO_PRECISION_DOUBLE = 0;
const llong MKL_PARDISO_PRECISION_SINGLE = 1;

const llong MKL_PARDISO_ZERO_NEG_PIVOTS = 29;

const llong MKL_PARDISO_PARTIAL_SOLVE_OPTION = 30;
const llong MKL_PARDISO_PARTIAL_SOLVE_SPARSE_RHS_PARTIAL = 1;
const llong MKL_PARDISO_PARTIAL_SOLVE_SPARSE_RHS_FULL = 2;
const llong MKL_PARDISO_PARTIAL_SOLVE_SELECTED = 3;

const llong MKL_PARDISO_OPTIMAL_THREADS = 33;

// This is not a mistake!
const llong MKL_PARDISO_INDEXING_OPTION = 34;
const llong MKL_PARDISO_INDEXING_ZERO = 1;
const llong MKL_PARDISO_INDEXING_ONE = 0;

const llong MKL_PARDISO_SCHUR_COMPLEMENT_OPTION = 35;
const llong MKL_PARDISO_SCHUR_COMPLEMENT_SOLVE = 1;
const llong MKL_PARDISO_SCHUR_COMPLEMENT_PARTIAL = 2;

const llong MKL_PARDISO_MATRIX_FORMAT_OPTION = 36;
const llong MKL_PARDISO_MATRIX_FORMAT_CSR = 0;
const llong MKL_PARDISO_MATRIX_FORMAT_BSR = 1;
const llong MKL_PARDISO_MATRIX_FORMAT_CONVERT_BSR = -1;

const llong MKL_PARDISO_PIVOT_OPTION = 55;
const llong MKL_PARDISO_PIVOT_CALLBACK = 1;

const llong MKL_PARDISO_OOC_OPTION = 59;
const llong MKL_PARDISO_OOC_OVERFLOW = 1;
const llong MKL_PARDISO_OOC_ALWAYS = 2;

const llong MKL_PARDISO_OOC_MIN_RAM = 62;

const llong MKL_PARDISO_MSG_QUIET = 0;
const llong MKL_PARDISO_MSG_VERBOSE = 1;
